# PayPal API credentials
paypal.clientId=AQC7hplnlfS5giiElVY056jxCX0akWVFwOyXJa-ylxORUDHbfSnFPvRtZ-sAVBenkvwmTWA79hBZ1rfG
paypal.clientSecret=EEa1U4ScNpz6PRxP6NT0ZqtmqhR_9_2UWHcwzSk76JHUhm7AnOizGXdCZNbeAyaqST5K2XX8NyU1TTdL
paypal.mode=sandbox